### PR TITLE
Implement 'p' packet

### PR DESCRIPTION
**Pull request by tromey**

### CODE REVIEW

**Comment by froydnj** [comment]
Nice, I was going to do this tomorrow.

**Comment by tromey** [comment]
This packet brings up some questions about how handlers will really work.  For example a gdbserver-like handler would want to keep state, so that the p packet can be implemented in terms of a register cache.  So maybe that is a mixin we should provide; but is this implementation possible with the current types?

**Comment by tromey** [comment]
Also, before writing stuff, you may want to pick bits out of https://github.com/tromey/rust-gdb-remote-protocol.  There is a fair amount of parsing logic there.

**Comment by luser** [comment]
Don't stress too much about the existing design of the non-parser bits. Calling it a design is giving it too much credit. Feel free to rewrite any of that as you see fit.

**Pull request merged**
