### PR TITLE
Add more command: continue, step, ...

### PR DESCRIPTION
**Pull request by yurydelendik**
Add support for:
- `qProcessInfo`
- `qRegisterInfo`
- `qSymbol`
- `c` -- continue
- `s` -- step

Extends support for 'H' -- supports different targets.

### CODE REVIEW

**Comment by tromey** [comment]
> The `c`/`s`/whatever packets are deprecated, see [the](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#index-H-packet) [wiki](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#index-c-packet)

FWIW they are only really deprecated if the remote supporst `vCont` -- but for a single-threaded remote, it's reasonable to not support it and to implement the older style.  Some stubs try to optimize for size and only handle a minimal number of packets -- though I'm not sure if rust-gdb-remote-protocol intends to ever support this mode.

See #26 for some info on the difficulties of `vCont` along with non-stop.  This may touch on this PR -- namely, should callbacks that run the inferior be synchronous or not.

**Comment by yurydelendik** [comment]
Not really sure how to use cfg() with nom macros -- added separate parser-functions

**Comment by yurydelendik** [comment]
> Let me know when you're done, and I'll merge this PR - it looks good!

@jD91mZM2 I think it is all set for this PR.

**Comment by jD91mZM2** [comment]
Sorry for the delay!

**Pull request merged**
